### ISSUE TITLE
Setup Initial Backend Project in Lyzer-BE Folder (chg-0002)

### ISSUE THREAD

**Issue by Evanlab02** [Evanlab02/Lyzer#2]
Need to setup initial Back-end for this project. 

Requirements:
- [x] First Endpoint (Schedule Endpoint) (No DB integration, this can be added later)
- [x] Docs Folder vs Wiki (Team discussion)
- [x] .gitignore
- [x] README.md
- [x] Makefile

**Comment by Pranav-Zodes-44** [comment]
- [ ] MongoDB integration
