### ISSUE TITLE
Research Code Analysis Tool (chg-0005)

### ISSUE THREAD

**Issue by Pranav-Zodes-44** [Evanlab02/Lyzer#5]

**Comment by Evanlab02** [comment]
https://sonarcloud.io/ is nice as it is free for open-source projects but does not have MonoRepo support for OpenSource Projects. This is a bit unfortunate as SonarCloud has alot of good features for Quality Gates and Bug catching. Will do more research but SonarCloud might be a bust.

**Comment by Evanlab02** [comment]
I will be closing this ticket as I think I have found a solution but we will only be able to implement this tool much later. Here are some docs for this when looking back:

https://docs.sonarcloud.io/advanced-setup/monorepo-support/
