### ISSUE TITLE
Add Hydrate All Schedules endpoint

### ISSUE THREAD

**Issue by Pranav-Zodes-44** [Evanlab02/Lyzer#73]
If ever we need to change the ScheduleDTO/RaceWeekendDTO, we should probably create a HydrateAllSchedules endpoint to allow us to somewhat automatically hydrate all schedules in the db instead of manually deleting all, since there will be a mismatch.

**Comment by Evanlab02** [comment]
On this, shouldn't endpoints automatically hydrate most of the time if there is no data, that way we do not have to hydrate all schedules. Should happen automatically when endpoints are pinged for the first time and there is no data?

**Comment by Pranav-Zodes-44** [comment]
@Evanlab02 Yeh, I'm honestly not too sure why I created this issue or when. Whether it was before or after I created that endpoint. Either way, this issue is redundant 😅
